opnfv-{{ lab.location }}{{ lab.racks[0].rack }}-maas:
opnfv:
{% set net_prefix = opnfv.spaces_dict.admin.cidr %}
  admNetgway: {{ opnfv.spaces_dict.admin.gateway }}
  admNetwork: {{ net_prefix | ipaddr('2') | ipaddr('address') }}
  admin_password: openstack
  ip_address: {{ os.brAdmIP }}
  maas_name: {{ lab.location }}{{ lab.racks[0].rack }}
  main_archive: http://archive.ubuntu.com/ubuntu
  upstream_dns: {{ lab.racks[0].dns }}
{% if opnfv.storage_dict.ceph is defined %}
  ceph-disk: {{ opnfv.storage_dict.ceph.disk }}
{% endif %}
{% if opnfv.spaces_dict.data is defined %}
{% set netdata_prefix = opnfv.spaces_dict.data.cidr %}
  dataNetwork: {{ opnfv.spaces_dict.data.cidr }}
{% endif %}
  domain: {{ lab.racks[0].osdomainname }}
  ext-port: {{ lab.racks[0]['ext-port'] }}
  ext_port: {{ lab.racks[0]['ext-port'] }}
  floating-ip-range: {{ lab.racks[0]['floating-ip-range'] }}
  interface-enable: {{ lab.racks[0].ifnamelist }}
  os-domain-name: {{ lab.racks[0].osdomainname }}
{% if opnfv.spaces_dict.public is defined %}
{% set netpublic_prefix = opnfv.spaces_dict.public.cidr %}
  publicNetwork: {{ opnfv.spaces_dict.public.cidr }}
{% endif %}
  spaces:
{% for net in opnfv.spaces %}
  - bridge: {{ net.bridge }}
    cidr: {{ net.cidr }}
    gateway: {{ net.gateway or '' }}
    type: {{ net.type }}
    vlan: {{ net.vlan or '' }}
{% endfor %}
  storage:
{% for storage in opnfv.storage %}
  - disk: {{ storage.disk }}
    type: {{ storage.type }}
{% endfor %}
{% if opnfv.spaces_dict.storage is defined %}
  storageNetwork: {{ opnfv.spaces_dict.storage.cidr }}
{% endif %}
  units: {{ lab.racks[0].nodes|count }}
  vip:
{% if opnfv.spaces_dict.public is defined %}
{% if opnfv.spaces_dict.data is defined %}
    ceilometer: {{ net_prefix | ipaddr('24') | ipaddr('address') }} {{ netdata_prefix | ipaddr('24') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('24') | ipaddr('address')}}
    cinder: {{ net_prefix | ipaddr('29') | ipaddr('address')}} {{ netdata_prefix | ipaddr('29') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('29') | ipaddr('address')}} 
    dashboard: {{ net_prefix | ipaddr('21') | ipaddr('address') }} {{ netdata_prefix | ipaddr('21') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('21') | ipaddr('address')}}
    glance: {{ net_prefix | ipaddr('22') | ipaddr('address') }} {{ netdata_prefix | ipaddr('22') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('22') | ipaddr('address')}}
    heat: {{ net_prefix | ipaddr('28') | ipaddr('address') }} {{ netdata_prefix | ipaddr('28') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('28') | ipaddr('address')}}
    keystone: {{ net_prefix | ipaddr('23') | ipaddr('address') }} {{ netdata_prefix | ipaddr('23') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('23') | ipaddr('address')}}
    mysql: {{ net_prefix | ipaddr('25') | ipaddr('address')}}
    neutron: {{ net_prefix | ipaddr('27') | ipaddr('address') }} {{ netdata_prefix | ipaddr('27') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('27') | ipaddr('address')}}
    nova: {{ net_prefix | ipaddr('26') | ipaddr('address') }} {{ netdata_prefix | ipaddr('26') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('26') | ipaddr('address')}}
{% else %}
    ceilometer: {{ net_prefix | ipaddr('24') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('24') | ipaddr('address')}}
    cinder: {{ net_prefix | ipaddr('29') | ipaddr('address')}} {{ netpublic_prefix | ipaddr('29') | ipaddr('address')}}
    dashboard: {{ net_prefix | ipaddr('21') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('21') | ipaddr('address')}}
    glance: {{ net_prefix | ipaddr('22') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('22') | ipaddr('address')}}
    heat: {{ net_prefix | ipaddr('28') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('28') | ipaddr('address')}}
    keystone: {{ net_prefix | ipaddr('23') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('23') | ipaddr('address')}}
    mysql: {{ net_prefix | ipaddr('25') | ipaddr('address')}}
    neutron: {{ net_prefix | ipaddr('27') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('27') | ipaddr('address')}}
    nova: {{ net_prefix | ipaddr('26') | ipaddr('address') }} {{ netpublic_prefix | ipaddr('26') | ipaddr('address')}}
{% endif %}
{% else %}
    ceilometer: {{ net_prefix | ipaddr('24') | ipaddr('address') }} 
    cinder: {{ net_prefix | ipaddr('29') | ipaddr('address')}}
    dashboard: {{ net_prefix | ipaddr('21') | ipaddr('address') }}
    glance: {{ net_prefix | ipaddr('22') | ipaddr('address') }}
    heat: {{ net_prefix | ipaddr('28') | ipaddr('address') }}
    keystone: {{ net_prefix | ipaddr('23') | ipaddr('address') }}
    mysql: {{ net_prefix | ipaddr('25') | ipaddr('address')}}
    neutron: {{ net_prefix | ipaddr('27') | ipaddr('address') }}
    nova: {{ net_prefix | ipaddr('26') | ipaddr('address') }}
{% endif %}
